version: "3.9"
services:
  db:
    image: postgres:16
    container_name: lexaro-postgres
    environment:
      POSTGRES_DB: lexaro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data   # keeps data in your repo folder

volumes:
  pgdata:



