version: "3.9"
services:
  db:
    image: postgres:16
    container_name: lexaro-postgres
    environment:
      POSTGRES_DB: lexaro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
